services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - /Users/bentojosedesantananeto/Documents/Cubos-Academy/Back/Modulo-04/CODIGO-AULA-CONSULTA-SQL/postgresdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
volumes:
  postgresdata:
